// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSgN0fNt6N4KI0JRkiefNIkEB8pRYq3yE',
    appId: '1:970403256337:web:6f4cb9c937d8cdda1079b0',
    messagingSenderId: '970403256337',
    projectId: 'hr-a4p',
    authDomain: 'hr-a4p.firebaseapp.com',
    storageBucket: 'hr-a4p.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAerojaPCvQ2eAbkz395T2kkOhFChf8FeE',
    appId: '1:970403256337:android:ca5a1a6a437930ba1079b0',
    messagingSenderId: '970403256337',
    projectId: 'hr-a4p',
    storageBucket: 'hr-a4p.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChuB2uqL8klyXsMVSwf3lUh0GuCv-3Hnk',
    appId: '1:970403256337:ios:0acfcdda45f7009d1079b0',
    messagingSenderId: '970403256337',
    projectId: 'hr-a4p',
    storageBucket: 'hr-a4p.appspot.com',
    iosBundleId: 'com.example.hr',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChuB2uqL8klyXsMVSwf3lUh0GuCv-3Hnk',
    appId: '1:970403256337:ios:0acfcdda45f7009d1079b0',
    messagingSenderId: '970403256337',
    projectId: 'hr-a4p',
    storageBucket: 'hr-a4p.appspot.com',
    iosBundleId: 'com.example.hr',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBSgN0fNt6N4KI0JRkiefNIkEB8pRYq3yE',
    appId: '1:970403256337:web:bd07b12e2ff360e01079b0',
    messagingSenderId: '970403256337',
    projectId: 'hr-a4p',
    authDomain: 'hr-a4p.firebaseapp.com',
    storageBucket: 'hr-a4p.appspot.com',
  );
}
